### ISSUE TITLE
Birim fiyat ve satır toplamı aynı

### ISSUE THREAD

**Issue by hkndmry** [Hasokeyk/elogo-php#1]
"tutar" olarak girilen rakam hem satır toplamı hem de birim fiyatı temsil ediyor. Satırdaki ürün miktarı birden fazla olduğunda ise satır toplamı birimi fiyat olarak kalmaya devam ediyor.

**Comment by Hasokeyk** [comment]
Merhabalar.

Bilgilendirme için teşekkür ederim. Test edip düzenlemeyi yayınlayacağım.

**Comment by hkndmry** [comment]
Teşekkürler. Aslında iskonto oranı, miktarı gibi daha da alt detaylar var. Bunlar da girilebiliyor olsa çok daha esnek olurdu. Elinize sağlık.

**Comment by Hasokeyk** [comment]
Kütüphane baştan yazıldı. O yüzden başlığı kapatıyorum.
