### ISSUE TITLE
UUID Hatası

### ISSUE THREAD

**Issue by OrhanOzyalcin** [Hasokeyk/elogo-php#4]
Kütüphanede bulunan UUID kısmına SessionID verildiğinden UUID geçersiz hatası veriyor.

**Comment by Hasokeyk** [comment]
Merhabalar,

Kullandığınız kodu paylabilir misiniz?

**Comment by OrhanOzyalcin** [comment]
Varsayılan kodları kullandığımız da bu hatayı aldık. Harici bir guid kullanarak aşabildik. 

efatura_kesme.php 85. Satır

            $fatura->setFaturaEttn($elogo_login->sessionID);
           


      Ek olarak fatura_notu tarafıyla ilgili de 

FaturaUbl.php dosyasında 131. satırda fatura_notu değişkeni ile ilgili hata görünüyor.
                $fatura_notu        = $this->fatura->fatura_notu ?? '';
