### ISSUE TITLE
FaturaUbl.php

### ISSUE THREAD

**Issue by OrhanOzyalcin** [Hasokeyk/elogo-php#6]
$musteri_vergi_dairesi kullanılmamış faturaya vergi dairesinin gitmediğini gördüm müsait zamanınızda bakabilirmisiniz?

**Comment by Hasokeyk** [comment]
Merhabalar,

Bir kaç gün pc den uzak olacağım ama pc geçince sizinle bir iletişime geçerek sorunları giderelim istiyorum. Tabi müsait olursanız

**Comment by OrhanOzyalcin** [comment]
Merhaba tekrar, çok iyi olur daha sonra kütüphaneyi kullanacak kişiler için. Nasıl iletişim kuralım?

**Comment by Hasokeyk** [comment]
https://hayatikodla.net/hayatikodla-iletisim/
